shared:
    image: node:8

parameters:
  p1: p1

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - step1: echo ok
    mainFreeze:
        requires: [main]
        # freezeWindows: [ "* 9-17 ? * 1-5" ]
        # freezeWindows: [ "* * ? * *" ]
        freezeWindows: ['* * ? 11 *']
        steps:
            - step1: echo ok
            - step2: echo $(meta get parameters.p1)
