# shared:
#     image: node:8

# parameters:
#   p1: p1

# jobs:
#     main:
#         requires: [~pr, ~commit]
#         steps:
#             - step1: echo ok
#     mainFreeze:
#         requires: [main]
#         # freezeWindows: [ "* 9-17 ? * 1-5" ]
#         # freezeWindows: [ "* * ? * *" ]
#         freezeWindows: ['* * ? 12 *']
#         steps:
#             - step1: echo ok
#             - step2: echo $(meta get parameters.p1)

shared:
    image: node:12

jobs:
  A:
    requires: [~pr, ~commit]
    steps:
      - ok: echo ok
  B:
    requires: [~pr, ~commit]
    steps:
      - ok: echo ok
  C:
    requires: [A]
    steps:
      - ok: echo ok
  D:
    requires: [C]
    steps:
      - ok: echo ok
  E:
    requires: [D]
    steps:
      - ok: echo ok
  F:
    requires: [A]
    steps:
      - ok: echo ok
  G:
    requires: [A]
    steps:
      - ok: echo ok
  H:
    requires: [A]
    steps:
      - ok: echo ok
  I:
    requires: [A]
    steps:
      - ok: echo ok
